package com.danielgergely.kgl

expect val GL_ACTIVE_TEXTURE: Int
expect val GL_DEPTH_BUFFER_BIT: Int
expect val GL_STENCIL_BUFFER_BIT: Int
expect val GL_COLOR_BUFFER_BIT: Int
expect val GL_FALSE: Int
expect val GL_TRUE: Int
expect val GL_POINTS: Int
expect val GL_LINES: Int
expect val GL_LINE_LOOP: Int
expect val GL_LINE_STRIP: Int
expect val GL_TRIANGLES: Int
expect val GL_TRIANGLE_STRIP: Int
expect val GL_TRIANGLE_FAN: Int
expect val GL_ZERO: Int
expect val GL_ONE: Int
expect val GL_SRC_COLOR: Int
expect val GL_ONE_MINUS_SRC_COLOR: Int
expect val GL_SRC_ALPHA: Int
expect val GL_ONE_MINUS_SRC_ALPHA: Int
expect val GL_DST_ALPHA: Int
expect val GL_ONE_MINUS_DST_ALPHA: Int
expect val GL_DST_COLOR: Int
expect val GL_ONE_MINUS_DST_COLOR: Int
expect val GL_SRC_ALPHA_SATURATE: Int
expect val GL_FUNC_ADD: Int
expect val GL_BLEND_EQUATION: Int
expect val GL_BLEND_EQUATION_RGB: Int
expect val GL_BLEND_EQUATION_ALPHA: Int
expect val GL_FUNC_SUBTRACT: Int
expect val GL_FUNC_REVERSE_SUBTRACT: Int
expect val GL_BLEND_DST_RGB: Int
expect val GL_BLEND_SRC_RGB: Int
expect val GL_BLEND_DST_ALPHA: Int
expect val GL_BLEND_SRC_ALPHA: Int
expect val GL_CONSTANT_COLOR: Int
expect val GL_ONE_MINUS_CONSTANT_COLOR: Int
expect val GL_CONSTANT_ALPHA: Int
expect val GL_ONE_MINUS_CONSTANT_ALPHA: Int
expect val GL_BLEND_COLOR: Int
expect val GL_ARRAY_BUFFER: Int
expect val GL_ELEMENT_ARRAY_BUFFER: Int
expect val GL_ARRAY_BUFFER_BINDING: Int
expect val GL_ELEMENT_ARRAY_BUFFER_BINDING: Int
expect val GL_STREAM_DRAW: Int
expect val GL_STATIC_DRAW: Int
expect val GL_DYNAMIC_DRAW: Int
expect val GL_BUFFER_SIZE: Int
expect val GL_BUFFER_USAGE: Int
expect val GL_CURRENT_VERTEX_ATTRIB: Int
expect val GL_FRONT: Int
expect val GL_BACK: Int
expect val GL_FRONT_AND_BACK: Int
expect val GL_TEXTURE_2D: Int
expect val GL_CULL_FACE: Int
expect val GL_BLEND: Int
expect val GL_DITHER: Int
expect val GL_STENCIL_TEST: Int
expect val GL_DEPTH_TEST: Int
expect val GL_SCISSOR_TEST: Int
expect val GL_POLYGON_OFFSET_FILL: Int
expect val GL_SAMPLE_ALPHA_TO_COVERAGE: Int
expect val GL_SAMPLE_COVERAGE: Int
expect val GL_NO_ERROR: Int
expect val GL_INVALID_ENUM: Int
expect val GL_INVALID_VALUE: Int
expect val GL_INVALID_OPERATION: Int
expect val GL_OUT_OF_MEMORY: Int
expect val GL_CW: Int
expect val GL_CCW: Int
expect val GL_LINE_WIDTH: Int
expect val GL_ALIASED_POINT_SIZE_RANGE: Int
expect val GL_ALIASED_LINE_WIDTH_RANGE: Int
expect val GL_CULL_FACE_MODE: Int
expect val GL_FRONT_FACE: Int
expect val GL_DEPTH_RANGE: Int
expect val GL_DEPTH_WRITEMASK: Int
expect val GL_DEPTH_CLEAR_VALUE: Int
expect val GL_DEPTH_FUNC: Int
expect val GL_STENCIL_CLEAR_VALUE: Int
expect val GL_STENCIL_FUNC: Int
expect val GL_STENCIL_FAIL: Int
expect val GL_STENCIL_PASS_DEPTH_FAIL: Int
expect val GL_STENCIL_PASS_DEPTH_PASS: Int
expect val GL_STENCIL_REF: Int
expect val GL_STENCIL_VALUE_MASK: Int
expect val GL_STENCIL_WRITEMASK: Int
expect val GL_STENCIL_BACK_FUNC: Int
expect val GL_STENCIL_BACK_FAIL: Int
expect val GL_STENCIL_BACK_PASS_DEPTH_FAIL: Int
expect val GL_STENCIL_BACK_PASS_DEPTH_PASS: Int
expect val GL_STENCIL_BACK_REF: Int
expect val GL_STENCIL_BACK_VALUE_MASK: Int
expect val GL_STENCIL_BACK_WRITEMASK: Int
expect val GL_VIEWPORT: Int
expect val GL_SCISSOR_BOX: Int
expect val GL_COLOR_CLEAR_VALUE: Int
expect val GL_COLOR_WRITEMASK: Int
expect val GL_UNPACK_ALIGNMENT: Int
expect val GL_PACK_ALIGNMENT: Int
expect val GL_MAX_TEXTURE_SIZE: Int
expect val GL_MAX_VIEWPORT_DIMS: Int
expect val GL_SUBPIXEL_BITS: Int
expect val GL_RED_BITS: Int
expect val GL_GREEN_BITS: Int
expect val GL_BLUE_BITS: Int
expect val GL_ALPHA_BITS: Int
expect val GL_DEPTH_BITS: Int
expect val GL_STENCIL_BITS: Int
expect val GL_POLYGON_OFFSET_UNITS: Int
expect val GL_POLYGON_OFFSET_FACTOR: Int
expect val GL_TEXTURE_BINDING_2D: Int
expect val GL_SAMPLE_BUFFERS: Int
expect val GL_SAMPLES: Int
expect val GL_SAMPLE_COVERAGE_VALUE: Int
expect val GL_SAMPLE_COVERAGE_INVERT: Int
expect val GL_NUM_COMPRESSED_TEXTURE_FORMATS: Int
expect val GL_COMPRESSED_TEXTURE_FORMATS: Int
expect val GL_DONT_CARE: Int
expect val GL_FASTEST: Int
expect val GL_NICEST: Int
expect val GL_GENERATE_MIPMAP_HINT: Int
expect val GL_BYTE: Int
expect val GL_UNSIGNED_BYTE: Int
expect val GL_SHORT: Int
expect val GL_UNSIGNED_SHORT: Int
expect val GL_INT: Int
expect val GL_UNSIGNED_INT: Int
expect val GL_FLOAT: Int
expect val GL_FIXED: Int
expect val GL_DEPTH_COMPONENT: Int
expect val GL_ALPHA: Int
expect val GL_RGB: Int
expect val GL_RGBA: Int
expect val GL_LUMINANCE: Int
expect val GL_LUMINANCE_ALPHA: Int
expect val GL_UNSIGNED_SHORT_4_4_4_4: Int
expect val GL_UNSIGNED_SHORT_5_5_5_1: Int
expect val GL_UNSIGNED_SHORT_5_6_5: Int
expect val GL_FRAGMENT_SHADER: Int
expect val GL_VERTEX_SHADER: Int
expect val GL_MAX_VERTEX_ATTRIBS: Int
expect val GL_MAX_VERTEX_UNIFORM_VECTORS: Int
expect val GL_MAX_VARYING_VECTORS: Int
expect val GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS: Int
expect val GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS: Int
expect val GL_MAX_TEXTURE_IMAGE_UNITS: Int
expect val GL_MAX_FRAGMENT_UNIFORM_VECTORS: Int
expect val GL_SHADER_TYPE: Int
expect val GL_DELETE_STATUS: Int
expect val GL_LINK_STATUS: Int
expect val GL_VALIDATE_STATUS: Int
expect val GL_ATTACHED_SHADERS: Int
expect val GL_ACTIVE_UNIFORMS: Int
expect val GL_ACTIVE_UNIFORM_MAX_LENGTH: Int
expect val GL_ACTIVE_ATTRIBUTES: Int
expect val GL_ACTIVE_ATTRIBUTE_MAX_LENGTH: Int
expect val GL_SHADING_LANGUAGE_VERSION: Int
expect val GL_CURRENT_PROGRAM: Int
expect val GL_NEVER: Int
expect val GL_LESS: Int
expect val GL_EQUAL: Int
expect val GL_LEQUAL: Int
expect val GL_GREATER: Int
expect val GL_NOTEQUAL: Int
expect val GL_GEQUAL: Int
expect val GL_ALWAYS: Int
expect val GL_KEEP: Int
expect val GL_REPLACE: Int
expect val GL_INCR: Int
expect val GL_DECR: Int
expect val GL_INVERT: Int
expect val GL_INCR_WRAP: Int
expect val GL_DECR_WRAP: Int
expect val GL_VENDOR: Int
expect val GL_RENDERER: Int
expect val GL_VERSION: Int
expect val GL_EXTENSIONS: Int
expect val GL_NEAREST: Int
expect val GL_LINEAR: Int
expect val GL_NEAREST_MIPMAP_NEAREST: Int
expect val GL_LINEAR_MIPMAP_NEAREST: Int
expect val GL_NEAREST_MIPMAP_LINEAR: Int
expect val GL_LINEAR_MIPMAP_LINEAR: Int
expect val GL_TEXTURE_MAG_FILTER: Int
expect val GL_TEXTURE_MIN_FILTER: Int
expect val GL_TEXTURE_WRAP_S: Int
expect val GL_TEXTURE_WRAP_T: Int
expect val GL_TEXTURE: Int
expect val GL_TEXTURE_CUBE_MAP: Int
expect val GL_TEXTURE_BINDING_CUBE_MAP: Int
expect val GL_TEXTURE_CUBE_MAP_POSITIVE_X: Int
expect val GL_TEXTURE_CUBE_MAP_NEGATIVE_X: Int
expect val GL_TEXTURE_CUBE_MAP_POSITIVE_Y: Int
expect val GL_TEXTURE_CUBE_MAP_NEGATIVE_Y: Int
expect val GL_TEXTURE_CUBE_MAP_POSITIVE_Z: Int
expect val GL_TEXTURE_CUBE_MAP_NEGATIVE_Z: Int
expect val GL_MAX_CUBE_MAP_TEXTURE_SIZE: Int
expect val GL_TEXTURE0: Int
expect val GL_TEXTURE1: Int
expect val GL_TEXTURE2: Int
expect val GL_TEXTURE3: Int
expect val GL_TEXTURE4: Int
expect val GL_TEXTURE5: Int
expect val GL_TEXTURE6: Int
expect val GL_TEXTURE7: Int
expect val GL_TEXTURE8: Int
expect val GL_TEXTURE9: Int
expect val GL_TEXTURE10: Int
expect val GL_TEXTURE11: Int
expect val GL_TEXTURE12: Int
expect val GL_TEXTURE13: Int
expect val GL_TEXTURE14: Int
expect val GL_TEXTURE15: Int
expect val GL_TEXTURE16: Int
expect val GL_TEXTURE17: Int
expect val GL_TEXTURE18: Int
expect val GL_TEXTURE19: Int
expect val GL_TEXTURE20: Int
expect val GL_TEXTURE21: Int
expect val GL_TEXTURE22: Int
expect val GL_TEXTURE23: Int
expect val GL_TEXTURE24: Int
expect val GL_TEXTURE25: Int
expect val GL_TEXTURE26: Int
expect val GL_TEXTURE27: Int
expect val GL_TEXTURE28: Int
expect val GL_TEXTURE29: Int
expect val GL_TEXTURE30: Int
expect val GL_TEXTURE31: Int
expect val GL_REPEAT: Int
expect val GL_CLAMP_TO_EDGE: Int
expect val GL_MIRRORED_REPEAT: Int
expect val GL_FLOAT_VEC2: Int
expect val GL_FLOAT_VEC3: Int
expect val GL_FLOAT_VEC4: Int
expect val GL_INT_VEC2: Int
expect val GL_INT_VEC3: Int
expect val GL_INT_VEC4: Int
expect val GL_BOOL: Int
expect val GL_BOOL_VEC2: Int
expect val GL_BOOL_VEC3: Int
expect val GL_BOOL_VEC4: Int
expect val GL_FLOAT_MAT2: Int
expect val GL_FLOAT_MAT3: Int
expect val GL_FLOAT_MAT4: Int
expect val GL_SAMPLER_2D: Int
expect val GL_SAMPLER_CUBE: Int
expect val GL_VERTEX_ATTRIB_ARRAY_ENABLED: Int
expect val GL_VERTEX_ATTRIB_ARRAY_SIZE: Int
expect val GL_VERTEX_ATTRIB_ARRAY_STRIDE: Int
expect val GL_VERTEX_ATTRIB_ARRAY_TYPE: Int
expect val GL_VERTEX_ATTRIB_ARRAY_NORMALIZED: Int
expect val GL_VERTEX_ATTRIB_ARRAY_POINTER: Int
expect val GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING: Int
expect val GL_IMPLEMENTATION_COLOR_READ_TYPE: Int
expect val GL_IMPLEMENTATION_COLOR_READ_FORMAT: Int
expect val GL_COMPILE_STATUS: Int
expect val GL_INFO_LOG_LENGTH: Int
expect val GL_SHADER_SOURCE_LENGTH: Int
expect val GL_SHADER_COMPILER: Int
expect val GL_SHADER_BINARY_FORMATS: Int
expect val GL_NUM_SHADER_BINARY_FORMATS: Int
expect val GL_LOW_FLOAT: Int
expect val GL_MEDIUM_FLOAT: Int
expect val GL_HIGH_FLOAT: Int
expect val GL_LOW_INT: Int
expect val GL_MEDIUM_INT: Int
expect val GL_HIGH_INT: Int
expect val GL_FRAMEBUFFER: Int
expect val GL_RENDERBUFFER: Int
expect val GL_RGBA4: Int
expect val GL_RGB5_A1: Int
expect val GL_RGB565: Int
expect val GL_DEPTH_COMPONENT16: Int
// GL_STENCIL_INDEX does not appear in gl2.h or gl2ext.h, and there is no
// token with value 0x1901.
//
@Deprecated("")
expect val GL_STENCIL_INDEX: Int
expect val GL_STENCIL_INDEX8: Int
expect val GL_RENDERBUFFER_WIDTH: Int
expect val GL_RENDERBUFFER_HEIGHT: Int
expect val GL_RENDERBUFFER_INTERNAL_FORMAT: Int
expect val GL_RENDERBUFFER_RED_SIZE: Int
expect val GL_RENDERBUFFER_GREEN_SIZE: Int
expect val GL_RENDERBUFFER_BLUE_SIZE: Int
expect val GL_RENDERBUFFER_ALPHA_SIZE: Int
expect val GL_RENDERBUFFER_DEPTH_SIZE: Int
expect val GL_RENDERBUFFER_STENCIL_SIZE: Int
expect val GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE: Int
expect val GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME: Int
expect val GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL: Int
expect val GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE: Int
expect val GL_COLOR_ATTACHMENT0: Int
expect val GL_DEPTH_ATTACHMENT: Int
expect val GL_STENCIL_ATTACHMENT: Int
expect val GL_NONE: Int
expect val GL_FRAMEBUFFER_COMPLETE: Int
expect val GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT: Int
expect val GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT: Int
expect val GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS: Int
expect val GL_FRAMEBUFFER_UNSUPPORTED: Int
expect val GL_FRAMEBUFFER_BINDING: Int
expect val GL_RENDERBUFFER_BINDING: Int
expect val GL_MAX_RENDERBUFFER_SIZE: Int
expect val GL_INVALID_FRAMEBUFFER_OPERATION: Int