name: Build + Publish Snapshot
on:
  push:
    branches:
      - '*'
      - '**'
jobs:
  gradle:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Fetch tags
        run: git pull --unshallow && git fetch --all --tags --depth=9999 && git describe --tags --abbrev=0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle Build
        run: ./gradlew build

      - name: Gradle Publish
        run: ./gradlew publish
        env:
          MAVEN_PUBLISH_URL: 'https://maven.danielgergely.com/snapshots'
          MAVEN_PUBLISH_USER: ${{ secrets.MAVEN_DANIELGERGELY_USER }}
          MAVEN_PUBLISH_PASS: ${{ secrets.MAVEN_DANIELGERGELY_PASSWORD }}